In [1]:
# Initialize Otter
import otter
grader = otter.Notebook("hw1.ipynb")

# Hw 1: Data Science Workflow and More NumPy 📈

Name:

Student ID:

Collaborators:

## Instructions

For this homework, we will be gaining more exposure to NumPy and exploring the data science workflow a little. **Important:** Ensure that all plots have the necessary components that a plot should have: axes labels and a title (and a legend when it is appropriate). You must have all components of a plot on every plot for the entire semester!

Work your way through these problems. They will provide some more practice for working with NumPy arrays. 
> Use NumPy arrays and functions in **all** problems unless explicitly stated otherwise! 

Frequently **save** your notebook!

### Collaborators and Sources
Furthermore, in addition to recording your **collaborators** on this homework, please also remember to **cite/indicate all external sources** used when finishing this assignment. 
> This includes peers, TAs, and links to online sources. 

Note that these citations will be taken into account during the grading and regrading process, **especially** when two or more submissions closely resemble each other. Working with each other is ok, as long as you cite who you worked with!

In [ ]:
# Sources:
# https://developers.google.com/edu/python/strings

# your code here
answer = 'my answer'

### Submission instructions
* As it was in HW 0 (and in every homework from here on out), submit this Python notebook on Gradescope.
* Don't forget to commit and push to your Github repo!
* **Do not change the number of cells!** Your submission notebook should have exactly one code cell per problem. 
* Do **not** remove the `# your code here` line. Add your solution **after** that line. 

## 1. Churn Analysis: Data Science Workflow

Consider the following data science use case:

> *Assume you just landed a great analytical job with MegaTelCo, one of the largest telecommunication firms in the United States. They are having a major problem with customer retention in their wireless business. In the mid-Atlantic region, 20% of cell phone customers leave when their contracts expire, and it is getting increasingly difficult to acquire new customers. Since the cell phone market is now saturated, the huge growth in the wireless market has tapered off. Communications companies are now engaged in battles to attract each other’s customers while retaining their own. Customers switching from one company to another is called churn, and it is expensive all around: one company must spend on incentives to attract a customer while another company loses revenue when the customer departs.*
>
> *You have been called in to help understand the problem and to devise a solution. Attracting new customers is much more expensive than retaining existing ones, so a good deal of marketing budget is allocated to prevent churn. Marketing has already designed a special retention offer. Your task is to devise a precise, step-by-step plan for how the data science team should use MegaTelCo’s vast data resources to decide which customers should be offered the special retention deal prior to the expiration of their contracts.*

<!-- BEGIN QUESTION -->


### Problem 1.1

**Write-up!** Is this a scientific, social, or business problem? Briefly justify your answer.

_Clearly a business problem. I am solving a problem for a business._

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

### Problem 1.2

**Write-up!** Using the **data science workflow** discussed in class, describe how you would takle this task. Think carefully about what data you might use and how they would be used. Also, how should MegaTelCo choose a set of customers to receive their offer in order to best reduce churn for a particular incentive budget?

_This is a classification problem. We need to figure out which customers are likely to renew their contracts on their own, and which ones will need a special deal to stay with us. Presumably, we already have clean, formatted data, so the first step is to explore the data, looking for patterns. Our target are customers who let their contract run out and do not renew it. We should be looking for correlations between other factors (customer demographics, which plan they're on, their location, their use habbits, whether or not they've had to contact support, how long they've been users, etc) and our target. Then, we should use that data to make predictions about the best customers to offer the retention deal to._

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 2. Social Network Analysis: Data Science Workflow

Consider the following data science use case.

> *Congratulations! You’ve just been hired to lead the data science efforts at DataSciencester, a not-for-profit  social network for data scientists. It’s your first day on the job at DataSciencester, and the VP of Networking is full of questions about the DataSciencester users.
In particular, he wants you to identify who the “key connectors” are among data scientists to better understand the data science community, its structure and the roles of its members.*

### Problem 2.1

**Write-up!** Is this a scientific, social, or business problem? Briefly justify your answer. 

_Considering this is for a nonprofit social network, I think it's safe to say that it's a social problem._

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

### Problem 2.2

**Write-up!** Using the **data science workflow** discussed in class, describe how you would takle this task. Think carefully about what data you might use and how they would be used to derive a solution and how you would present the results to the VP of Networking. 

_This is a clustering problem. We need to identify the "key connectors" by looking at the data we already have from DataSciencester. One way is to look for the users who have the most interactions with the widest variety of people, and who recieve a lot of interaction themselves. High follower count and high number of people followed would also be good stats to look for. Using this info, we can ID the key connectors algorithmically, then select the best ones and write a report about them to show the VP of Networking._

<!-- END QUESTION -->

## 3. Practice NumPy Indexing

Indexing, especially with NumPy, can be a tricky feature to truly wrap one's head around, but the benefits of (working towards) mastering it make it a worthy endeavor. The more practice you get, the easier it will become — eventually you won't be able to even imagine how else you would do things.

In this section, we will start with some review and then move on to more complex features.

### Basic Indexing
At the risk of belaboring this topic, let's quickly do some practicing. The following cell produces `yet_another_array` using the `np.random.randint` function, which we will use in the next few problems.

In [2]:
import numpy as np
yet_another_array = np.random.randint(11, size=10)
yet_another_array

array([0, 2, 1, 4, 5, 9, 1, 9, 3, 7])

### Problem 3.1

**Do this!** Retrieve the 4th element of `yet_another_array`.

*Note: this question has hidden tests, or is graded on style of code and not just answer alone.*

In [18]:
element = yet_another_array[3]
element

4

### Problem 3.2

Here's something new: specifically for NumPy arrays, you can also pass in a Python list or NumPy array of indicies to retrieve.

For example, `some_array[[0, 2, 4, 6]]`.


**Do this!** Retrieve the 2nd, 5th, and 9th elements of `yet_another_array`.

*Note: this question has hidden tests, or is graded on style of code and not just answer alone.*

In [19]:
elements = yet_another_array[[1,4,8]]

In [17]:
grader.check("q3b")

q3b results: All test cases passed!

### Problem 3.3

Let's do this with a 2D array, too. Here we will generate `a_2d_array` using the `np.random.rand` function.

*Note: this question has hidden tests, or is graded on style of code and not just answer alone.*

In [20]:
a_2d_array = np.random.rand(5, 5)
a_2d_array

array([[0.37955321, 0.44889481, 0.73271511, 0.06955591, 0.63397622],
       [0.73927117, 0.00149746, 0.77843017, 0.03099758, 0.00121768],
       [0.06953797, 0.53595841, 0.04722535, 0.67153778, 0.01473794],
       [0.54057146, 0.39248131, 0.91723568, 0.8466558 , 0.962548  ],
       [0.89827357, 0.16250371, 0.05396798, 0.7884798 , 0.4803585 ]])

Remember that you can index into a 2D array like this: `another_2D_array[row, column]`, where `row` and `column` are indicies, slices, `:`s, or some mix of these three.

**Do this!** Retrieve the value at index `(3, 4)` from `a_2d_array`.

In [22]:
a_2d_element = a_2d_array[3,4]
a_2d_element

0.9625480030675951

### Slice Indexing

You've already gotten familiar with slices, but here is some more practice.

### Problem 3.4

**Do this!** Retrieve the 6th, 7th, and 8th elements of `yet_another_array`.

*Note: this question has hidden tests, or is graded on style of code and not just answer alone.*

In [23]:
more_elements = yet_another_array[[5,6,7]]

In [24]:
grader.check("q3d")

q3d results: All test cases passed!

### Problem 3.5

Here is a reminder of what `a_2d_array` looks like.

*Note: this question has hidden tests, or is graded on style of code and not just answer alone.*

In [25]:
a_2d_array

array([[0.37955321, 0.44889481, 0.73271511, 0.06955591, 0.63397622],
       [0.73927117, 0.00149746, 0.77843017, 0.03099758, 0.00121768],
       [0.06953797, 0.53595841, 0.04722535, 0.67153778, 0.01473794],
       [0.54057146, 0.39248131, 0.91723568, 0.8466558 , 0.962548  ],
       [0.89827357, 0.16250371, 0.05396798, 0.7884798 , 0.4803585 ]])

**Do this!** Retrieve the values in the 3rd column of `a_2d_array`.

In [26]:
column = a_2d_array[:,2]

In [27]:
grader.check("q3e")

q3e results: All test cases passed!

### Logical Indexing

Now for something complete new! You might be interested in finding all of the values in an array that fulfills some condition like _get all values greater than 5_. 

> [🐍 **Python Feature** 🐍]: NumPy enables this by supporting [**Boolean (or logical) indexing**](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.indexing.html#boolean-or-mask-index-arrays).

This idea is also referred to as **masking**. You can use an array of boolean values _of the same shape_ as the target array as the "index" into the target array. This will return all of the values that are in the same position as the `True` values from the boolean arrays. These logical arrays are called "masks" because they are analogous to masks, which let some of the underlying surface show through, but hide the rest.

Let's try making our first logical array. In the cell below, we use a comparison operation on `yet_another_array`, returning an array of the same size with `True` in the positions where the values meet the condition.

In [28]:
yet_another_array > 5

array([False, False, False, False, False,  True, False,  True, False,
        True])

Now let's see how this array "lines up" with `yet_another_array`.

In [29]:
yet_another_array

array([0, 2, 1, 4, 5, 9, 1, 9, 3, 7])

Here is another example using an array that is not sorted already.

In [30]:
shuffled_array = np.random.permutation(yet_another_array)
shuffled_array

array([1, 0, 7, 3, 9, 9, 5, 4, 2, 1])

In [31]:
shuffled_array > 5

array([False, False,  True, False,  True,  True, False, False, False,
       False])

Is this what you would expect? Let's actually get those values.

In [32]:
shuffled_array[shuffled_array > 5]

array([7, 9, 9])

### Problem 3.6

**Do this!** Retrieve the elements of `yet_another_array` that are even (hint: `%`).

*Note: this question has hidden tests, or is graded on style of code and not just answer alone.*

In [36]:
even_array = yet_another_array[yet_another_array%2==0]
even_array

array([0, 2, 4])

## 4. Model Evaluation and More Numpy


### Error Measure

Lets assume we have the following predictions `y_pred` and observed targets `y_true` for evaluation. 

In [39]:
y_hat = np.array([0, 2, 1, 2, 1, 0, 0, 2, 1, 0, 1, 0, 2, 1, 2, 1, 1, 
                   0, 2, 0, 0, 1, 0, 2, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 
                   0, 0, 2, 1, 0, 0, 2, 2, 0, 1, 1])
y_test = np.array([0, 2, 2, 2, 1, 0, 0, 1, 2, 0, 1, 0, 2, 1, 2, 1, 1,
                   0, 2, 0, 0, 1, 0, 2, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 
                   0, 0, 2, 1, 0, 0, 2, 2, 0, 1, 1])

### Problem 4.1

**Do this!** Complete the following function so that given two arrays of labels, `y_test` and `y_hat`, it will return the average classification error, `avg_err`. Use **Boolean operations** on the arrays instead of a for loop.

*Note: this question has hidden tests, or is graded on style of code and not just answer alone.*

In [69]:
def avg_error(y_true, y_pred):
    '''
    Computes the classification error given Y_TRUE and Y_PRED
    as a value from 0 to 1
    '''
    
    avg_err = y_pred[y_pred!=y_true].shape[0]/y_pred.shape[0]
    return avg_err

In [70]:
err_score = avg_error(y_hat, y_test)
print(f'Error: {100*err_score:0.2f}%')

Error: 6.67%


<!-- BEGIN QUESTION -->

**Write-up!** How does the _average classification error_ computed above relate to the _average classification accuracy_ that you computed in Lab0? State a mathematical formula of how you can compute the average error from the average accuracy. 

_Average classification error is 1-average accuracy._

<!-- END QUESTION -->

### Evaluating a Model using all the Features

As you might have concluded in your communication your findings step, one way to imporve our predictions could be to use all the features instead of just one. Lets do that now and compare the results. We saved the processed data for you. This is the same data that you created and used in Lab1. 

In [56]:
data = np.load('utility/data/processed_iris_data.npy')
data[:5,:]
data

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

### Problem 4.2

**Do this!** Create `X` and `y` arrays. Now with X including all four features. Then reproduce the steps from Lab1 (D. Building and evaluating a model and making predictions). 

*Note: this question has hidden tests, or is graded on style of code and not just answer alone.*

In [58]:
X, y = data[:,:4],data[:,4]
...

### Problem 4.3

**Do this!** Make the training and testing sets exactly with the same configuration as in Lab1. 
> Note: This is **very important** since it will let us compare the new results with the ones we got in the lab (since we are using the _same_ training and test splits).

*Note: this question has hidden tests, or is graded on style of code and not just answer alone.*

In [59]:
from sklearn.model_selection import train_test_split

# train_test_split will be used a lot in this class, be sure to remember how to use it!
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=217)
...

Ellipsis

### Problem 4.4

**Do this!** Train the Model on the training data that you created in the previous step. 

*Note: this question has hidden tests, or is graded on style of code and not just answer alone.*

In [60]:
from utility.util import SimpleModel
model = SimpleModel()


In [61]:
model.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [62]:
grader.check("q4d")

q4d results: All test cases passed!

### Problem 4.5

**Do this!** Make predictions on the test set and compare them to the ground truth by computing the average classification error. 
> **Hint:** use your `avg_error()` function from above. 

*Note: this question has hidden tests, or is graded on style of code and not just answer alone.*

In [71]:
predictions = model.predict(X_test)

score = avg_error(predictions, y_test)

print(f'Avg Error: {100*score:0.2f}%')

Avg Error: 4.44%


In [64]:
grader.check("q4e")

q4e results: All test cases passed!

<!-- BEGIN QUESTION -->

### Problem 4.6

**Write-up!** Report your average classification error (the grader cannot see your notebook!) and provide a conclusion on whether we were able to imporve the model by using all the features.   

_It went from 93.33 to 95.56% accurate, so it was improved by using all features._

<!-- END QUESTION -->

And that's it!

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [66]:
grader.check_all()

q3a results: All test cases passed!

q3b results: All test cases passed!

q3c results: All test cases passed!

q3d results: All test cases passed!

q3e results: All test cases passed!

q3f results: All test cases passed!

q4ai results: All test cases passed!

q4b results: All test cases passed!

q4c results: All test cases passed!

q4d results: All test cases passed!

q4e results: All test cases passed!

## Submission

Make sure you have run all cells in your notebook in order before running the cell below, so that all images/graphs appear in the output. The cell below will generate a zip file for you to submit. **Please save before exporting!**

In [72]:
# Save your notebook first, then run this cell to export your submission.
grader.export(pdf=False)